version: '3.9'

services:
  database:
    image: postgres
    container_name: system_pregao
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=system
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local